# Generated by Django 5.1 on 2024-09-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='Categories/imgs/default.jpg', upload_to='Categories/imgs/%y/%m/%d/'),
        ),
    ]
