name: Deploy Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # or your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        run: |
          python manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: your_project.settings
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # Example for using a database URL

      - name: Deploy to Heroku (or other platforms)
        run: |
          git remote add heroku https://git.heroku.com/your-heroku-app.git
          git push heroku main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Notify deployment
        run: echo "Deployment complete!"

